# Linter:
# https://github.com/brigade/scss-lint
# Lint Defaults:
# https://github.com/brigade/scss-lint/blob/master/config/default.yml
# Lint Definitions:
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

scss_files: app/assets/stylesheets/

# Excluding our legacy css files
exclude: [
  'app/assets/stylesheets/960.scss',
  'app/assets/stylesheets/_base.scss',
  'app/assets/stylesheets/_bootstrap_and_overrides.scss',
  'app/assets/stylesheets/_legacy-overrides.scss',
  'app/assets/stylesheets/account.scss',
  'app/assets/stylesheets/admin_reports.scss',
  'app/assets/stylesheets/api.scss',
  'app/assets/stylesheets/application.scss',
  'app/assets/stylesheets/buttons.scss',
  'app/assets/stylesheets/cells.scss',
  'app/assets/stylesheets/dialog.scss',
  'app/assets/stylesheets/doorkeeper.scss',
  'app/assets/stylesheets/forms.scss',
  'app/assets/stylesheets/global.scss',
  'app/assets/stylesheets/global_scripts.scss',
  'app/assets/stylesheets/global_scripts_codemirror.css',
  'app/assets/stylesheets/header.scss',
  'app/assets/stylesheets/invitations.scss',
  'app/assets/stylesheets/ip_filters.scss',
  'app/assets/stylesheets/jquery*',
  'app/assets/stylesheets/leads.scss',
  'app/assets/stylesheets/lists.scss',
  'app/assets/stylesheets/main.scss',
  'app/assets/stylesheets/page*',
  'app/assets/stylesheets/preview.scss',
  'app/assets/stylesheets/primary-nav.scss',
  'app/assets/stylesheets/reset.scss',
  'app/assets/stylesheets/select2.scss',
  'app/assets/stylesheets/static.scss',
  'app/assets/stylesheets/tables.scss',
  'app/assets/stylesheets/template-picker.scss',
  'app/assets/stylesheets/ui.scss',
  'app/assets/stylesheets/users.scss',
  'app/assets/stylesheets/codemirror/*',
]

linters:
  BorderZero:
    enabled: true
    convention: none

  ColorVariable:
    enabled: false

  DeclarationOrder:
    enabled: false

  ExtendDirective:
    enabled: true

  MergeableSelector:
    enabled: true
    force_nesting: false

  NestingDepth:
    enabled: true
    max_depth: 1
    ignore_parent_selectors: true

  PropertySortOrder:
    enabled: false

  PseudoElement:
    enabled: false

  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: false

  SelectorDepth:
    enabled: true
    max_depth: 2

  SelectorFormat:
    enabled: false

  SpaceAfterVariableColon:
    enabled: true
    style: one_space

  TrailingZero:
    enabled: true

  TransitionAll:
    enabled: true

  VariableForProperty:
    enabled: true
    properties:
      - color
      - font
